### ISSUE TITLE
ToDo List after Hackathon

### ISSUE THREAD

**Issue by fiore** [fiore/CreativeMarketplace-Chainhack-Hackathon#1]
At the hackathon time and knowledge were few . So a refactor is necessary.

- [ ] Mock an ICO
- [ ] Unit Test with Truffle
- [ ] Refactor main Smart Contract, adding more functionalities
